export * from './interfaces'

export {default as Parallax} from './Parallax'
export {default as ParallaxBack} from './ParallaxBack'
export {default as ParallaxBottomLeft} from './ParallaxBottomLeft'
export {default as ParallaxBottomRight} from './ParallaxBottomRight'
export {default as ParallaxContent} from './ParallaxContent'
export {default as ParallaxFront} from './ParallaxFront'
export {default as ParallaxTopLeft} from './ParallaxTopLeft'
export {default as ParallaxTopRight} from './ParallaxTopRight'
